CREATE DATABASE phpmyadmin;
GRANT SELECT, INSERT, UPDATE, DELETE ON phpmyadmin.* TO 'pma'@'%' IDENTIFIED BY 'Xibaochat!';
GRANT ALL PRIVILEGES ON *.* TO 'sammy'@'%' IDENTIFIED BY 'Xibaochat!' WITH GRANT OPTION;
FLUSH PRIVILEGES;
