apiVersion: apps/v1
kind: Deployment
metadata:
  name: baobe-deployment
  labels:
    app: baobe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baobe
  template:
    metadata:
      labels:
        app: baobe
    spec:
      volumes:
      - configMap:
          name: telegraf-config
        name: telegraf-config
      containers:
      - name: baobe
        image: baobe:00
        volumeMounts:
        - mountPath: /root
          name: telegraf-config
          readOnly: true
        ports:
        - containerPort: 5050
