---
apiVersion: v1
kind: Service
metadata:
  name: baobe-service-http
spec:
  type: LoadBalancer
  selector:
    app: baobe
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
