apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
  labels:
    app: pma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      volumes:
      - configMap:
          name: telegraf-config
        name: telegraf-config
      containers:
      - name: pma
        image: pma:00
        volumeMounts:
        - mountPath: /root
          name: telegraf-config
          readOnly: true
        ports:
        - containerPort: 80
