apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-volume
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
   path: "/home/baobe/volume2"
