apiVersion: v1
data:
  secretkey: MlhOQUMyWXBCT3V3TXNITGFXeCtWalZIYzFlR0dwVTBZVXEyd0dqYkpPU1FDWlhlUzU5NGpDSUlUT3BsS2ozNwpwUmNnaDNkQjlDNnNMY1BYanErZEo1MUorKzNBZG5yUUhrN29sTTNUeUIraGdHZDNmTzVYUFNEdXo3clRadnZMCnB6cXM5SUM3bVJqR0oxOWdBbVpMNE9EM3JsM3NLazM5YXNhMGovTmo3N2c9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
