apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      volumes:
      - configMap:
          name: telegraf-config
        name: telegraf-config
      containers:
      - name: ftps
        image: ftps:00
        volumeMounts:
        - mountPath: /root
          name: telegraf-config
          readOnly: true
        ports:
        - containerPort: 21
        - containerPort: 30019
        - containerPort: 30020
